# Generated by Django 5.2.3 on 2025-12-06 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
